# Generated by Django 5.0.1 on 2024-01-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0003_contact_us_alter_filter_price_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='number',
        ),
    ]
