# Generated by Django 5.0.1 on 2024-01-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
