# Generated by Django 5.0.1 on 2024-01-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0008_order_paid_order_paymentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
