# Generated by Django 5.0.1 on 2024-01-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0011_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='review_desp',
        ),
    ]
