# Generated by Django 5.0.1 on 2024-02-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0015_alter_wishlist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Relatedproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='Eapp.product')),
                ('related', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Eapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Eapp.product'),
        ),
    ]
