# Generated by Django 5.0.1 on 2024-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0017_delete_relatedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
