# Generated by Django 5.0.1 on 2024-02-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0018_orderitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
